apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfProject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rfproject
  template:
    metadata:
      labels:
        app: rfproject
    spec:
      containers:
        - name: rfproject
          image: neocpx/rfproject:latest
          ports:
            - containerPort: 8080
